   Neoplasm.Disease.Stage.American.Joint.Committee.on.Cancer.Code       American.Joint.Committee.on.Cancer.Publication.Version.Type 
                                                             TRUE                                                              TRUE 
                                                 Aneuploidy.Score                                               Buffa.Hypoxia.Score 
                                                             TRUE                                                              TRUE 
Last.Communication.Contact.from.Initial.Pathologic.Diagnosis.Date                      Birth.from.Initial.Pathologic.Diagnosis.Date 
                                                             TRUE                                                              TRUE 
                                            Disease.Free..Months.                               Months.of.disease.specific.survival 
                                                             TRUE                                                              TRUE 
                                 Disease.specific.Survival.status                                                Ethnicity.Category 
                                                             TRUE                                                              TRUE 
                                          Fraction.Genome.Altered                                            Genetic.Ancestry.Label 
                                                             TRUE                                                              TRUE 
    Neoadjuvant.Therapy.Type.Administered.Prior.To.Resection.Text                                                  MSI.MANTIS.Score 
                                                             TRUE                                                              TRUE 
                                                  MSIsensor.Score                                                    Mutation.Count 
                                                             TRUE                                                              TRUE 
                New.Neoplasm.Event.Post.Initial.Therapy.Indicator                                     Person.Neoplasm.Cancer.Status 
                                                             TRUE                                                              TRUE 
                                  Progress.Free.Survival..Months.                        Primary.Lymph.Node.Presentation.Assessment 
                                                             TRUE                                                              TRUE 
                                                  Prior.Diagnosis                                                     Race.Category 
                                                             TRUE                                                              TRUE 
                                                Radiation.Therapy                                              Ragnum.Hypoxia.Score 
                                                             TRUE                                                              TRUE 
                                                          Subtype                           Tissue.Prospective.Collection.Indicator 
                                                             TRUE                                                              TRUE 
                        Tissue.Retrospective.Collection.Indicator                                               TMB..nonsynonymous. 
                                                             TRUE                                                              TRUE 
                                             Winter.Hypoxia.Score                           Binary.Disease.specific.Survival.status 
                                                             TRUE                                                              TRUE 
